name: Validate with hassfest  # 工作流名称：使用 Hassfest 工具进行验证

on:  # 触发条件
  push:  # 当代码推送到仓库时触发
  pull_request:  # 当创建拉取请求时触发
  #schedule:  # 定时触发
    #- cron: "0 0 * * *"  # 每天 UTC 时间 00:00 运行

jobs:  # 定义任务
  validate:  # 任务标识符：验证
    runs-on: "ubuntu-latest"  # 运行环境：最新版 Ubuntu 系统
    steps:  # 任务步骤
      - uses: "actions/checkout@v2"  # 使用版本 2 的 checkout 操作，检出代码
      - uses: home-assistant/actions/hassfest@master  # 使用 Hassfest 操作（主分支），进行 Home Assistant 集成验证
